name: gero_neuro_kine_calendar
description: Calendario profesional para Gero Neuro Kine
publish_to: 'none'
version: 1.4.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Calendar
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9
  intl: ^0.19.0

  # State Management
  provider: ^6.1.1

  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # Google Calendar Integration
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  google_sign_in: ^6.2.1

  # Utilities
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
