name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.0'

    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --verbose

    - name: List build outputs
      run: |
        echo "Build directory contents:"
        ls -la build/app/outputs/flutter-apk/ || echo "Directory not found"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gero-neuro-kine-calendar
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: error
